# ===== DEVICE IDENTITY =====
SITE = "SITE_A"
ASSET = "PUMP_01"
DEVICE = "EDGE_PUMP_01"
FIRMWARE = "L1_v2.0"

# ===== SIGNAL CONFIG =====
FS = 1024
WINDOW_SIZE = 1024

# ===== THRESHOLDS =====
ACC_RMS_ALARM = 0.3
VEL_WARNING = 2.8
VEL_ALARM = 4.5
CREST_LIMIT = 4.0
HF_LIMIT = 0.1

# ===== WIFI =====
WIFI_SSID = "YOUR_SSID"
WIFI_PASSWORD = "YOUR_PASSWORD"

# ===== MQTT =====
MQTT_BROKER = "127.0.0.1"
MQTT_PORT = 1883

# ===== WATCHDOG =====
WDT_TIMEOUT_SEC = 8
LOOP_DELAY_SEC = 1

