# SYSTEM IDENTITY
SITE  = "SITE_A"
ASSET = "PUMP_01"
DEVICE_ID = "EDGE_001"
FIRMWARE_VERSION = "1.0.0"

# SYSTEM MODE
MODE = "PC"       # PC | ESP32

# SAMPLING CONFIG
FS = 1024
N  = 1024

# COMMUNICATION
COMM_MODE = "AUTO"
NETWORK_MODE = "DUAL"
NETWORK_PRIORITY = "LAN_FIRST"

# WIFI
WIFI_SSID = "Factory_WiFi"
WIFI_PASSWORD = "12345678"

# ETHERNET
ETHERNET_ENABLED = True
ETH_DHCP = True
ETH_IP = "192.168.1.100"
ETH_GATEWAY = "192.168.1.1"
ETH_SUBNET = "255.255.255.0"

# MQTT
MQTT_BROKER = "127.0.0.1"
MQTT_PORT = 1883
CLIENT_ID = "EDGE_PUMP_01"
MQTT_BASE_TOPIC = "vibration/l1"
MQTT_QOS = 1
MQTT_USER = "user"
MQTT_PASSWORD = "password"
MQTT_RETRY_SEC = 5

# USB
SERIAL_BAUDRATE = 115200

# THRESHOLDS
VEL_WARNING = 2.8
VEL_ALARM = 4.5
ACC_RMS_WARNING = 0.3
ACC_RMS_ALARM = 0.5
CREST_WARNING = 3.0
CREST_ALARM = 4.5
HF_WARNING = 0.2
HF_ALARM = 0.35

# HEALTH INDEX WEIGHT
WEIGHT_ACC   = 0.4
WEIGHT_VEL   = 0.3
WEIGHT_CREST = 0.2
WEIGHT_HF    = 0.1

# WATCHDOG
WDT_TIMEOUT_SEC = 10

# LOGGING
LOG_ENABLE = True
LOG_PATH = "/sdcard/logs"
